[phases.setup]
nixPkgs = ["python311", "pip", "gcc", "g++"]

[phases.install] 
cmds = [
    "cd backend",
    "pip install --no-cache-dir -r requirements.txt"
]

[phases.build]
cmds = ["echo 'Build phase completed'"]

[start]
cmd = "cd backend && uvicorn server:app --host 0.0.0.0 --port $PORT"