[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
startCommand = "cd backend && python -m uvicorn server:app --host 0.0.0.0 --port ${PORT:-8000}"

[env]
PORT = "8000"