[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PORT = "8001"
AI_ENABLED = "false"
BLOCKCHAIN_ENABLED = "false"  
COMPLIANCE_ENABLED = "true"
POLYGON_NETWORK = "mainnet"
POLYGON_CHAIN_ID = "0x89"